from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('articles/', views.article_list, name='article_list'),
    path('mrp/', views.mrp_view, name='mrp_view'),
    path('capacity/', views.capacity_view, name='capacity_view'),
    path('decalages/', views.offset_graph_view, name='offset_graph_view'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/new/', views.order_create, name='order_create'),
    path('orders/<int:pk>/confirm/', views.order_confirm, name='order_confirm'),
    path('generate-of/', views.generate_of, name='generate_of'),
    path('manufacturing/', views.mo_list, name='mo_list'),
    path('manufacturing/<int:pk>/close/', views.mo_close, name='mo_close'),
    path('workorders/<int:pk>/<str:status>/', views.workorder_status, name='workorder_status'),
    path('maintenance/', views.maintenance_list, name='maintenance_list'),
    path('maintenance/new/', views.maintenance_create, name='maintenance_create'),
    path('supplier-orders/', views.supplier_order_list, name='supplier_order_list'),
    path('supplier-orders/new/', views.supplier_order_create, name='supplier_order_create'),
    path('supplier-receipts/', views.supplier_receipt_list, name='supplier_receipt_list'),
    path('supplier-receipts/new/', views.supplier_receipt_create, name='supplier_receipt_create'),
    path('supplier-invoices/', views.supplier_invoice_list, name='supplier_invoice_list'),
    path('supplier-invoices/new/', views.supplier_invoice_create, name='supplier_invoice_create'),
    path('production-costs/', views.production_cost_list, name='production_cost_list'),
    path('production-costs/new/', views.production_cost_create, name='production_cost_create'),
    path('quality-checks/', views.quality_check_list, name='quality_check_list'),
    path('quality-checks/new/', views.quality_check_create, name='quality_check_create'),
    path('non-conformities/', views.non_conformity_list, name='non_conformity_list'),
    path('non-conformities/new/', views.non_conformity_create, name='non_conformity_create'),
    path('certificates/', views.certificate_list, name='certificate_list'),
    path('certificates/new/', views.certificate_create, name='certificate_create'),
    path('preventive-maintenance/', views.preventive_maintenance_list, name='preventive_maintenance_list'),
    path('preventive-maintenance/new/', views.preventive_maintenance_create, name='preventive_maintenance_create'),
    path('spare-parts/', views.spare_part_list, name='spare_part_list'),
    path('spare-parts/new/', views.spare_part_create, name='spare_part_create'),
    path('holidays/', views.holiday_list, name='holiday_list'),
    path('gantt/', views.gantt_chart, name='gantt_chart'),
    path('machine-status/', views.machine_status, name='machine_status'),
    path('production-planning/', views.production_planning, name='production_planning'),
]
